name: Publish to npm
on:
  push:
    branches:
      - master

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      LastVersion: $ {{ steps.versions.outputs.LastVersion }}
      CurrentVersion: $ {{ steps.versions.outputs.CurrentVersion }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: |
          git checkout HEAD^
          echo "LastVersion=$(node -p 'require(`./package.json`).version')" >> "$GITHUB_OUTPUT"
          git checkout master
          echo "CurrentVersion=$(node -p 'require(`./package.json`).version')" >> "$GITHUB_OUTPUT"
        id: versions
  
  publish:
    needs: versions
    runs-on: ubuntu-latest
    if: ${{ needs.versions.outputs.LastVersion != needs.versions.outputs.CurrentVersion }}

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish

  sync-bridge:
    needs: publish
    runs-on: ubuntu-latest
    if: ${{ needs.versions.outputs.LastVersion != needs.versions.outputs.CurrentVersion }}
    steps:
      - run: ls
