name: Publish to npm
on:
  push:
    branches:
      - master

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      last: ${{ steps.versions.outputs.last }}
      current: ${{ steps.versions.outputs.current }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: |
          git checkout HEAD^
          echo "::set-output name=last::$(node -p 'require(`./package.json`).version')"
          git checkout master
          echo "::set-output name=current::$(node -p 'require(`./package.json`).version')" 
        id: versions
      - run: echo "${{steps.versions.outputs.last}},${{steps.versions.outputs.current}} "
  
  publish:
    needs: versions
    runs-on: ubuntu-latest
    if: ${{ needs.versions.outputs.last !=  needs.versions.outputs.current}}

    steps:
    - name: publish to npm
      uses: JS-DevTools/npm-publish@v1
      with:
        package: package.json
        token: ${{ secrets.NPM_TOKEN }}

  sync-bridge:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - run: ls
